added operator id to Originator
electrumpayments/service-interface-base pull request #50
Opened 2020-08-12 14:38 UTC by simone-van-zyl

We have added a new field to the Originator object called operatorId. It is a String with max length 30.

2020-08-13 07:22 UTC, VeeneshJeena commented on src/main/java/io/electrum/vas/model/Originator.java
>     public boolean equals(Object o) {
Update the equals, hashcode and toString methods

2020-08-13 07:24 UTC, VeeneshJeena commented on pom.xml
> +  <version>3.28.0</version>
Update release notes. Release notes are hidden in src/docs/hugo/site/content/release-notes.md

2020-08-13 07:25 UTC, TimElectrum commented on src/main/java/io/electrum/vas/model/Originator.java
> +   @Valid
Hmm, I'm not sure we need `@Valid` on simple fields (i.e. ones which aren't JSON objects).

You can confirm this by adding to the `recursiveValidationOnSubFieldsDataProvider` in `NewModelTests`

2020-08-13 07:25 UTC, TimElectrum commented on src/main/java/io/electrum/vas/model/Originator.java
>     public boolean equals(Object o) {
please update the `equals`, `hashCode` and `toString` methods too

2020-08-13 07:32 UTC, simone-van-zyl commented on src/main/java/io/electrum/vas/model/Originator.java
> +   @Valid
I thought this might be the case! I tried adding to the `recursiveValidationOnSubFieldsDataProvider` but it didn't pass. Will remove.

2020-08-20 07:28 UTC, TimElectrum requested changes
Please add to the `recursiveValidationOnSubFieldsDataProvider`. You said you did but it failed which smells fishy to me. We should understand why it failed and fix the code/test so it doesn't fail. Just removing the test because it failed is a bit like sticking our head in the sand.

2020-08-20 07:28 UTC, TimElectrum commented on src/main/java/io/electrum/vas/model/Originator.java
> +      sb.append("    operatorId: ").append(Utils.toIndentedString(operatorId)).append("\n");
check the SonarQube comment about calling `append(String)` but passing in a string of length 1. Rather use `append(char)`. Please also fix this for the above lines too.

2020-08-20 07:28 UTC, TimElectrum commented on pom.xml
> -  <version>3.27.0</version>
please make final

2020-08-20 07:28 UTC, TimElectrum commented on src/docs/devguide/hugo/site/content/release-notes.md
> +Released 13 August 2020
don't forget to update this

2020-08-20 08:06 UTC, simone-van-zyl commented on src/test/java/io/electrum/vas/model/NewModelTests.java
> +              {new Transaction().id("123456ID").originator(new Originator()), new Transaction().id("123456ID").originator(new Originator().operatorId("operatorId"))}
@TimElectrum This is the test that I added which failed. I'm not entirely sure why. The recursive validation still confuses me.

2020-08-20 11:29 UTC, simone-van-zyl commented on src/test/java/io/electrum/vas/model/NewModelTests.java
> +              {new Originator().terminalId("terminal").operatorId("String with more than thirty chars")
@TimElectrum, please check my new test

2020-08-20 12:03 UTC, TimElectrum approved these changes

2020-08-20 12:03 UTC, TimElectrum commented on src/test/java/io/electrum/vas/model/NewModelTests.java
> +              {new Originator().terminalId("terminal").operatorId("String with more than thirty chars")
the test you added is good but maybe add another with the 'valid' `Originator.operatorId` set to `null` to confirm that it's optional

2020-08-20 13:03 UTC, TimElectrum approved these changes

2020-08-20 13:16 UTC, merged