Adding a mobile wallet payment method.
electrumpayments/service-interface-base pull request #52
Opened 2021-02-05 08:23 UTC by mpendulocele-electrum

Hi @TimElectrum 

Can you kindly review the changes to support mobile wallet payments.

Kind regards
Mpendulo

2021-02-05 09:21 UTC, TimElectrum requested changes

2021-02-05 09:21 UTC, TimElectrum commented on src/main/java/io/electrum/vas/model/MobileWalletPayment.java
> +    private String walletProviderId;
I don't know if we need the provider ID as a field of the `MobileWalletPayment`:

- None of the other `PaymentMethod` derivatives carry such a field so why is a wallet special?
- For a particular transaction, the `receiver` field is meant to indicate this.
- We're going to add an `issuer` field of type `Institution` to the parent `PaymentMethod` anyway which would make this field redundant.

I think you can remove this field for now

2021-02-05 09:21 UTC, TimElectrum commented on src/main/java/io/electrum/vas/model/MobileWalletPayment.java
> +public class MobileWalletPayment extends PaymentMethod {
Hmm, Is there a difference between a _mobile_ wallet and a plain wallet? I don't think so, so perhaps we should rename this to simply `WalletPayment` - or maybe even just `Wallet`

2021-02-05 09:21 UTC, TimElectrum commented on src/main/java/io/electrum/vas/model/PaymentMethod.java
> +      REWARD("REWARD"),
again, just make sure to keep the order unchanged

2021-02-05 09:44 UTC, mpendulocele-electrum commented on src/main/java/io/electrum/vas/model/Account.java
> +// For the sake of correct deserialization, we need to map from values of type to child model classes explicitly
Resolved

2021-02-05 09:44 UTC, mpendulocele-electrum commented on src/main/java/io/electrum/vas/model/Account.java
> +      SWIFT("SWIFT");
Resolved

2021-02-05 10:18 UTC, mpendulocele-electrum commented on src/main/java/io/electrum/vas/model/MobileWalletPayment.java
> +        return Objects.equals(walletId, that.walletId) && Objects.equals(walletProviderId, that.walletProviderId);
Resolved

2021-02-05 10:19 UTC, mpendulocele-electrum commented on src/main/java/io/electrum/vas/model/MobileWalletPayment.java
> +    private String walletProviderId;
Resolved

2021-02-05 10:27 UTC, mpendulocele-electrum commented on src/main/java/io/electrum/vas/model/MobileWalletPayment.java
> +public class MobileWalletPayment extends PaymentMethod {
Resolved

2021-02-05 10:27 UTC, mpendulocele-electrum commented on src/main/java/io/electrum/vas/model/PaymentMethod.java
> +      REWARD("REWARD"),
Resolved

2021-02-05 10:28 UTC, mpendulocele-electrum commented on src/main/java/io/electrum/vas/model/MobileWalletPayment.java
> +        return Objects.equals(walletId, that.walletId) && Objects.equals(walletProviderId, that.walletProviderId);
Resolved

2021-02-08 12:47 UTC, TimElectrum reviewed
Thanks, I'm happy with the changes you've made. But we still want to make other changes to the API as part of this project so let's not merge just yet.

Also, you need to bump the version and add to the release notes.

2021-03-03 14:31 UTC, sowen123 commented
@TimElectrum should the walletId also be masked?

2021-03-04 07:04 UTC, TimElectrum requested changes
A few tweaks requested here and there.

2021-03-04 07:04 UTC, TimElectrum commented on src/test/java/io/electrum/vas/model/NewModelTests.java
> +                      .proxy("12345").proxyType(ProxyType.UNKNOWN).pin(new PinEncrypted().type(Pin.PinType.ENCRYPTED_PIN))}
just curious - is there a reason you added new elements before and after the existing one for the `Originator`?

It's harder to ensure that nothing changed for the `Originator` element if it's buried in amongst other, new, additions. If you're adding to a list of some sort, it's much easier to always add to the end of the list unless there's a specific reason not to.

2021-03-04 07:06 UTC, TimElectrum commented
> @TimElectrum should the walletId also be masked?

Hmm, it probably should be - it can be used to identify a customer

2021-03-04 15:04 UTC, sowen123 commented on src/main/java/io/electrum/vas/model/AccountPayment.java
> +      sb.append("    proxy: ").append(Utils.toIndentedString(proxy)).append("\n");
Ok cool I've fixed all of these now :)

2021-03-04 15:04 UTC, sowen123 commented on src/main/java/io/electrum/vas/model/AccountPayment.java
> +      sb.append("    destCustomerId: ").append(Utils.toIndentedString(destCustomerId)).append("\n");      sb.append("}");
Added it to the release notes :)

2021-03-04 15:05 UTC, sowen123 commented on src/main/java/io/electrum/vas/model/CardPayment.java
> -   public CardPayment pin(Pin pin) {
Yeah I didn't think this through thanks I've put them back

2021-03-04 15:05 UTC, sowen123 commented on src/main/java/io/electrum/vas/model/PaymentMethod.java
> +   @ApiModelProperty(value = "An alternative identifier for the customer's source of funds.")
I've changed this description now. Is that better?

2021-03-04 15:06 UTC, sowen123 commented on src/main/java/io/electrum/vas/model/ProxyType.java
> +    }
Hmmm not sure but I see all our other enum classes have a toString but only some have the `@JsonValue` annotation. For now I've added this in because otherwise you're right, it doesn't make sense why we would need it

2021-03-04 15:07 UTC, sowen123 commented on src/test/java/io/electrum/vas/model/NewModelTests.java
> +                      .proxy("12345").proxyType(ProxyType.UNKNOWN).pin(new PinEncrypted().type(Pin.PinType.ENCRYPTED_PIN))}
I didn't actually add those wallet payment tests but I've moved them now so their with the other tests I added :)

2021-03-04 15:07 UTC, sowen123 commented
> > @TimElectrum should the walletId also be masked?
> 
> Hmm, it probably should be - it can be used to identify a customer

Yeah I thought that as well. I've added masking on it now

2021-03-05 07:07 UTC, TimElectrum commented on src/docs/devguide/hugo/site/content/release-notes.md
> +* Changed format of toString for `AccountPayment` model.
```suggestion
* Changed format of `toString` output for `AccountPayment` model to match the general format of `toString` for other models.
```

2021-03-05 07:07 UTC, TimElectrum commented on src/main/java/io/electrum/vas/model/AccountPayment.java
> +      sb.append("    proxy: ").append(Utils.toIndentedString(proxy)).append("\n");
you say you've fixed it but I still see double quotes...

2021-03-05 07:07 UTC, TimElectrum commented on src/main/java/io/electrum/vas/model/An32TokenPayment.java
> +      sb.append('}');
ah, you fixed the curly brace but not the newlines

```suggestion
      sb.append("    name: ").append(Utils.toIndentedString(name)).append('\n');
      sb.append("    type: ").append(Utils.toIndentedString(type)).append('\n');
      sb.append("    amount: ").append(Utils.toIndentedString(amount)).append('\n');
      sb.append("    issuer: ").append(Utils.toIndentedString(issuer)).append('\n');
      sb.append("    pin: ").append(Utils.toIndentedString(pin)).append('\n');
      sb.append("    proxy: ").append(Utils.toIndentedString(proxy)).append('\n');
      sb.append("    proxyType: ").append(Utils.toIndentedString(proxyType)).append('\n');
      sb.append("    token: ").append(Utils.toIndentedString(token)).append('\n');
      sb.append('}');
```

2021-03-05 07:07 UTC, TimElectrum commented on src/main/java/io/electrum/vas/model/PaymentMethod.java
> +           "the customer identifier. E.g. a customer's MSISDN or email address")
```suggestion
   @ApiModelProperty(value = "An alternative identifier for the customer's source of funds. Acts as a stand in for " +
           "the customer identifier. E.g. a customer's MSISDN or email address.")
```

2021-03-05 07:07 UTC, TimElectrum commented on src/main/java/io/electrum/vas/model/ProxyType.java
> +    }
well your serialisation and deserialisation tests were working just fine without the `@JsonValue` so I'd say just drop the whole method it doesn't seem necessary.

2021-03-05 07:10 UTC, TimElectrum requested changes
just some pedantic comments.

I see Patrick is also making some changes [here](https://github.com/electrumpayments/service-interface-base/pull/53/files). Do you mind pulling those into your PR and then I'll give it a last look? It's probably easiest to copy the changes manually rather than using `git merge` across your branches but I'll leave that up to you.

When that's ready, you can also set the release date in the release notes because it should be ready to release at that point.

2021-03-05 13:44 UTC, TimElectrum approved these changes
Approved 🥳

2021-03-05 13:44 UTC, TimElectrum commented on src/docs/devguide/hugo/site/content/release-notes.md
> +* Updated the `maven-javadoc-plugin` from version `3.1.1` to version `3.2.0`.
it might be helpful to distinguish between API changes vs just Java changes:

```suggestion
* Added `WalletPayment` method.
* Added `amount`, `proxy`, `proxyType`, `issuer` and `pin` fields to the `PaymentMethod` model.
* Changes to the Java implementation of the base API:
  * Changed the format of `toString` output for `AccountPayment` model to match the general format of `toString` for other models.
  * The service interface base was updated to compile on Java 11.
  * Updated the `jaxb-core` dependency from version `2.2.11` to version `2.3.0`.
    * Removes warnings brought about when compiling on Java 9 or higher.
  * Updated the `jaxb-api` and jaxb-impl dependency from version `2.2.11` to version `2.3.1`.
    * Removes warnings brought about when compiling on Java 9 or higher.
  * Updated the `joda-time` dependency from version `2.9.4` to version `2.10.5`.
  * Updated the `jackson-datatype-joda` dependency from version `2.9.5` to version `2.10.0`.
  * Updated the `jackson-datatype-jdk8` dependency from version `2.8.5` to version `2.11.2`.
  * Updated the `jackson-datatype-jsr310` dependency from `2.8.5` to `2.11.2`.
  * Updated the `maven-javadoc-plugin` from version `3.1.1` to version `3.2.0`.
```

Happy to leave this at your discretion though

2021-03-05 14:18 UTC, merged