Added new `PaymentMethod` child called `QrPayment`.
electrumpayments/service-interface-base pull request #56
Opened 2021-05-05 06:31 UTC by PatrickColborne

* New `PaymentMethod` child called `QrPayment` which can be used when making a QR-based payment.
* Small double line change that was bothering me.

Asana board task for reference: https://app.asana.com/0/1199599476334023/1200226355899919/f

2021-05-05 08:47 UTC, TimElectrum requested changes

2021-05-05 08:47 UTC, TimElectrum commented on release-notes.md
> +## Version 3.31.0 - 5 May 2021
do you mind moving all of these release notes to the release notes webpage in the documentation? That makes it easy to copy/paste it into each API's own webpages when this change is rolled out to the other APIs. You'll see that there are already a bunch of release notes there so we can keep everything in one place then too

2021-05-05 08:47 UTC, TimElectrum commented on src/main/java/io/electrum/vas/model/QrPayment.java
> +   @Masked
I don't think this is sensitive, it can be unmasked

2021-05-05 08:47 UTC, TimElectrum commented on src/main/java/io/electrum/vas/model/QrPayment.java
> +   @ApiModelProperty(required = true, value = "The unique transaction identifier related to this transaction.")
I think it's worth pointing out that this is the value embedded in sub-Tag 00 of the Electrum MAIT. We should probably link to more comprehensive QR documentation to further explain but we don't have any of that yet 😞

2021-05-05 08:47 UTC, TimElectrum commented on release-notes.md
> +## Version 3.31.0 - 5 May 2021
in fact, you can leave a little note here pointing out the above to the next dev so that it's apparent and we don't have to make someone else sad by asking them to move their work

2021-05-05 08:47 UTC, TimElectrum commented on release-notes.md
>  * Validation constraints on `addressLine1` and `addressLine2` of the `Address` model object were incorrect. They were
so this was a breaking change...

It's very naughty but I'm okay with glossing over the breaking nature of this change since we introduced it ourselves for our own project and it was quite recent i.e. I don't think it's been widely adopted and I don't think we'll actually break any real projects. But we should highlight the breaking nature in the release notes and mark this version as deprecated so that no one builds upon it

2021-05-05 08:47 UTC, TimElectrum commented on src/main/java/io/electrum/vas/model/QrPayment.java
> +            .toString();
take a look at the `toString` for the other models - please stick to that format for consistency

2021-05-05 08:47 UTC, TimElectrum commented on src/main/java/io/electrum/vas/model/WalletPayment.java
>  package io.electrum.vas.model;
please revert this whole file - there aren't any real changes so this is just noise

2021-05-05 08:47 UTC, TimElectrum commented on src/test/resources/messages/models/QrPayment.json
> +  },
maybe just remove this entirely - it's too much effort to think about whether this is a valid `EncryptedPin` without an actual PIN value

2021-05-05 10:32 UTC, PatrickColborne commented on release-notes.md
>  * Validation constraints on `addressLine1` and `addressLine2` of the `Address` model object were incorrect. They were
Will do.

2021-05-05 14:02 UTC, TimElectrum requested changes
couple of small things

2021-05-05 14:02 UTC, TimElectrum commented on src/docs/devguide/hugo/site/content/release-notes.md
> +### Deprecated
SUV has some examples of how we mark things as deprecated: https://electrumpayments.github.io/suv-service-interface-docs/specification/release-notes/

2021-05-05 14:02 UTC, TimElectrum commented on src/docs/devguide/hugo/site/content/release-notes.md
> +* New `PaymentMethod` child called `QrPayment` which can be used when making a QR-based payment.
```suggestion
* Added a new `PaymentMethod` child called `QrPayment` which can be used when making a QR-based payment.
```

2021-05-05 14:02 UTC, TimElectrum commented on src/docs/devguide/hugo/site/content/release-notes.md
> +Released 5 May 2021
don't forget to update this date

2021-05-05 14:02 UTC, TimElectrum commented on src/main/java/io/electrum/vas/model/QrPayment.java
> + * @since v1.31.0
Missed this in the last round, my bad

```suggestion
 * @since v3.31.0
```

2021-05-05 14:02 UTC, TimElectrum commented on src/main/java/io/electrum/vas/model/WalletPayment.java
> +
please revert this, it's noise

2021-05-05 14:08 UTC, TimElectrum requested changes

2021-05-05 14:08 UTC, TimElectrum commented on src/main/java/io/electrum/vas/model/QrPayment.java
> +      sb.append('}');
hmm, where did you find this style from? Looking at `PaymentMethod` for example, the style should be something like:
```
      StringBuilder sb = new StringBuilder("class QrPayment{\n");
      sb.append("    type: ").append(Utils.toIndentedString(type)).append('\n');
      sb.append("    name: '").append(Utils.toIndentedString(name)).append('\n');
      sb.append("    amount: ").append(Utils.toIndentedString(amount)).append('\n');
      sb.append("    issuer: ").append(Utils.toIndentedString(issuer)).append('\n');
      sb.append("    pin: ").append(Utils.toIndentedString(pin)).append('\n');
      sb.append("    proxy: ").append(Utils.toIndentedString(proxy)).append('\n');
      sb.append("    proxyType: ").append(Utils.toIndentedString(proxyType)).append('\n');
      sb.append("    tranId: ").append(Utils.toIndentedString(tranId)).append('\n');
      sb.append("    partnerPaymentToken: ").append(Utils.toIndentedString(partnerPaymentToken).append('\n');
      sb.append('}');
```

2021-05-17 10:55 UTC, TimElectrum requested changes
there are some unresolved/unaddressed comments from previous reviews - please feel free to chat to me about any of it if you'd like.

Also, please add some tests for the new channel stuff

2021-05-17 10:55 UTC, TimElectrum commented on src/main/java/io/electrum/vas/model/QrPayment.java
> +   @ApiModelProperty(required = true, value = "The unique transaction identifier related to this transaction. The tranId is embedded in sub-Tag 00 of the Electrum MAIT.")
MAITs only mean something in the context of EMVCo.

```suggestion
   @ApiModelProperty(required = true, value = "The unique transaction identifier related to this transaction. In QRs styled on the EMVCo specification, the tranId is embedded in sub-Tag 00 of the Electrum MAIT.")
```

2021-05-17 10:55 UTC, TimElectrum commented on src/docs/devguide/hugo/site/content/release-notes.md
> +Released 14 May 2021
Just going to leave this reminder here until I'm ready to approve the PR

2021-05-17 10:55 UTC, TimElectrum commented on src/main/java/io/electrum/vas/model/Transaction.java
> -import java.util.ArrayList;
please revert all of these changes - this class has no functional changes so these just add noise to the PR

2021-05-17 10:55 UTC, TimElectrum commented on src/main/java/io/electrum/vas/model/Originator.java
> +    * The ID that uniquely identifies the channel that this transaction was received through.
```suggestion
    * The ID that uniquely identifies the originator's channel that this transaction was received through.
```

2021-05-17 10:55 UTC, TimElectrum commented on src/main/java/io/electrum/vas/model/Originator.java
> +   @ApiModelProperty(required = false, value = "The ID that uniquely identifies the channel that this transaction was received through.")
```suggestion
   @ApiModelProperty(required = false, value = "The ID that uniquely identifies the originator's channel that this transaction was received through.")
```

2021-05-17 10:55 UTC, TimElectrum commented on src/main/java/io/electrum/vas/model/Originator.java
> +   @Length(max = 30)
The airtime API already has [ChannelProductListing](https://electrumpayments.github.io/airtime-service-interface-docs/specification/definitions/#channelproductlisting) which has a max length of 50 for the `channelName`. I don't think we need to explicitly define the name as equal to or not equal to the ID but since the `channelName` is already defined, I can imagine the `channelName` value also being used as the ID in which case I think we should make this field a little longer to match `channelName`:

```suggestion
   @Length(max = 50)
```

2021-05-18 07:35 UTC, TimElectrum requested changes

2021-05-18 08:34 UTC, TimElectrum approved these changes

2021-05-18 08:34 UTC, TimElectrum commented on src/docs/devguide/hugo/site/content/release-notes.md
> +Released 14 March 2021
why is this changing? It was merged to `master` on 5 March...

2021-05-18 08:38 UTC, merged