Added new REWARD tender type
electrumpayments/service-interface-base pull request #63
Opened 2021-07-26 12:27 UTC by Liam-Watson

Became needed as part of Vodacom telco rewards.

2021-07-26 13:55 UTC, BR00KE requested changes
Other than small release notes change I think we can go straight to final version because it's such a small addition.

@Liam update pom version

2021-07-26 13:55 UTC, BR00KE commented on src/docs/devguide/hugo/site/content/release-notes.md
> +* Added new `REWARD` tender type for telco rewards.
We don't need to specify telco rewards.

2021-07-26 14:01 UTC, simone-van-zyl commented on src/main/java/io/electrum/vas/model/Tender.java
> +      REWARD("REWARD"),
I think we should be careful about changing the order of enum values 
![image](https://user-images.githubusercontent.com/52028676/127001657-df23766a-a6ad-4e71-b63d-737133200e2d.png)
https://docs.oracle.com/javase/tutorial/java/javaOO/enum.html
Rather add the new tendertype last in the list

2021-07-26 14:03 UTC, simone-van-zyl requested changes
Remember to update the Readme with the new version number

2021-07-26 14:11 UTC, BR00KE approved these changes

2021-07-27 06:59 UTC, Shaaheen approved these changes
LGTM

2021-07-27 07:09 UTC, merged