Feature 3-D Secure
electrumpayments/service-interface-base pull request #64
Opened 2021-11-12 13:44 UTC by CaseyODonnell92

At time of pull request, the following is outstanding:
- Proper descriptions of new models and fields.
- Final decision regarding how to represent verification results.
- Recursive validation testing of the new models.
- Validation rules on new models.

2021-11-18 06:45 UTC, TimElectrum commented on src/main/java/io/electrum/vas/model/ThreeDSecureData.java
> +   }
we tend to put `enums` at the top of the class

2021-11-22 09:00 UTC, mpendulocele-electrum requested changes
Thanks Casey.

I have added a few comments.

2021-11-24 11:41 UTC, CaseyODonnell92 commented on src/main/java/io/electrum/vas/model/ThreeDSecureData.java
> +      Y, N, U, A, C, D, R, I, S
I like the idea, but the names do get a bit unwieldy. For example, both `C` and `D` denote a "Challenge Required" state, but they have qualifiers like "Additional authentication is required using the CReq/CRes" (C) and "Decoupled Authentication confirmed" (D). 
Since we're directly representing values from the 3DS specification, I'm tempted to just use their encoding. Any integrators that need to use this model will most likely be familiar with the values as defined in the EMVCo specification. Let me know what you think.

2021-11-25 08:38 UTC, mpendulocele-electrum approved these changes
LGTM;

The code duplication stuff issuer detected by sonarqube does not seem to be worth solving.

2021-11-26 07:48 UTC, merged