Feature add transaction labels
electrumpayments/service-interface-base pull request #71
Opened 2022-02-11 12:36 UTC by mpendulocele-electrum

2022-02-14 11:44 UTC, CaseyODonnell92 requested changes
@VeeneshJeena had some good ideas about what characters we should accept for label values. Please check in with him! Otherwise this looks good. I've made some documentation suggestions, let me know what you think of them.

2022-02-14 11:44 UTC, CaseyODonnell92 commented on src/main/java/io/electrum/vas/model/TransactionLabel.java
> +   @ApiModelProperty(required = true, value = "Label name used to uniquely identifier the transaction label.")
```suggestion
   @ApiModelProperty(required = true, value = "Label name that indicates the type and intended use of the transaction label. The meaning of label names must be agreed upon by the parties involved in transaction processing.")
```
What do you think of this?

2022-02-14 11:44 UTC, CaseyODonnell92 commented on src/main/java/io/electrum/vas/model/TransactionLabel.java
> +   public String getName() {
We should give this a length cap. Perhaps up to 100 characters?

2022-02-14 11:44 UTC, CaseyODonnell92 commented on src/main/java/io/electrum/vas/model/TransactionLabel.java
> +   public String getValue() {
For this value, we definitely want to prohibit putting something like escaped JSON or other potentially processable message data in this field. So it should definitely be length-capped. And I think we should allow 1) alphanumeric characters (including uppercase), 2) whitespace like spaces and tabs and 3) a limited set of special characters. @VeeneshJeena, you had some ideas about which characters to include, please weigh in!
At the very least, I think we should allow underscores and dashes.

2022-02-14 15:19 UTC, VeeneshJeena requested changes

2022-02-14 15:19 UTC, VeeneshJeena commented on src/docs/devguide/hugo/site/content/release-notes.md
> +Released 11 February 2022
Date reminder

2022-02-14 15:19 UTC, VeeneshJeena commented on src/main/java/io/electrum/vas/model/Transaction.java
> +      }
Should we allow setting to null, which in turn clears the labels?

2022-02-14 15:19 UTC, VeeneshJeena commented on src/main/java/io/electrum/vas/model/TransactionLabel.java
> +   public String getName() {
Let's get some restrictions on what we can use as a label name.
For starters, we can go with only the following:
- Alpha
- Numeric
- Underscores

2022-02-14 15:19 UTC, VeeneshJeena commented on src/main/java/io/electrum/vas/model/TransactionLabel.java
> +   public String getValue() {
I think we should allow:
- Alpha (upper and lower case)
- Numeric
- Spaces. We shouldn't allow tabs. I can't think of a reason why someone would want tabs in the value, when they can rather use spaces.
- Underscores
- Dashes/hyphens
- I'm on the fence about open and close round parenthesis, `(` and `)`. The only reason I can think of this is sometimes values can be written as the value, with extra info in brackets. A silly example: `Airtime (R5)'

2022-02-14 15:19 UTC, VeeneshJeena commented on src/main/java/io/electrum/vas/model/TransactionLabel.java
> +   @ApiModelProperty(required = true, value = "Label name that indicates the type and intended use of the transaction label. The meaning of label names must be agreed upon by the parties involved in
```suggestion
   @ApiModelProperty(required = true, value = "Label name that indicates the type and intended use of the transaction label. The label names and meaning of label names must be agreed upon by the parties involved in transaction processing.")
```

2022-02-14 15:19 UTC, VeeneshJeena commented on src/main/java/io/electrum/vas/model/TransactionLabel.java
> +   @ApiModelProperty(required = true, value = "Label name that indicates the type and intended use of the transaction label. The meaning of label names must be agreed upon by the parties involved in
Can I ask that we get a BA, like Fabrizio, involved in reading this description.
I suggest this because our BA's typically have to explain to a customer what this means when the customer reads on API docs, so at least they can get some input into how this field is described.

Also, our BA's are technical, but not dev technical, so it will be helpful to know if at least they understand what we mean.

2022-02-15 06:26 UTC, CaseyODonnell92 commented on src/main/java/io/electrum/vas/model/TransactionLabel.java
> +   public String getValue() {
It might be safer to leave them out for now. Making validation more restrictive can break an API whereas making it more permissive is not breaking. So we can always add things later

2022-02-15 06:31 UTC, CaseyODonnell92 commented on src/main/java/io/electrum/vas/model/Transaction.java
> +      }
It's currently annotated as `@NotNull`, so it makes sense to not accept null values. I think if the annotation stays, we should not allow null values. But the question should maybe be whether the list should ever be null. The only benefit I see is that it won't get serialised if it is null.

2022-02-15 06:36 UTC, CaseyODonnell92 requested changes
Just a quick review to ask that the runtime exception be removed. Let's wait to hear from Fabrizio about the verbiage. And we just need to finalise the validation constraints. The code, however, is probably in a position where we can release a release candidate and starting drafting up the translation changes where this will get used.

2022-02-15 06:36 UTC, CaseyODonnell92 commented on src/main/java/io/electrum/vas/model/Transaction.java
>        }
```suggestion
```
The annotation is enough, I think runtime exceptions are a bit extreme

2022-02-15 07:27 UTC, VeeneshJeena commented on src/main/java/io/electrum/vas/model/Transaction.java
> +      }
What I meant is,
if (transactionLabels == null) {
        // we don't want it to be null, but if given null, we want to clear the values
         this.transactionLabels = new ArrayList<>(); 
      }


TransactionLabels in itself is not a mandatory field, so throwing an exception when someone gives null, especially a runtime exception, is harsh.
TransactionLabels in this case is an ordinary POJO field in Transaction, so there's no reason why it can't accept null.

How is this field different to the other fields in Transaction, or even the other List field, thirdPartyIdentifiers?

2022-02-15 07:29 UTC, VeeneshJeena commented on src/main/java/io/electrum/vas/model/TransactionLabel.java
> +   public String getValue() {
To be clear, which ones do you want to leave out? The parenthesis?

2022-02-15 07:33 UTC, CaseyODonnell92 commented on src/main/java/io/electrum/vas/model/Transaction.java
> +      }
`thirdPartyIdentifiers` is actually marked `@NotNull`, and so is actually required. So we _should_ be prohibiting setting it null (which we aren't). I see what you mean about clearing the values on null. Personally, I don't like the idea of passing null to a field to set it to a new empty list, since it's not an obvious method contract. I would prefer a dedicated method to "clear" them or to mandate that callers pass in their own empty list. What do you reckon?

2022-02-15 07:38 UTC, CaseyODonnell92 commented on src/main/java/io/electrum/vas/model/TransactionLabel.java
> +   public String getValue() {
Sorry, ya I meant the parenthesis. I don't feel strongly about it, just that it's safer to realise we need them later than to realise later we shouldn't have added them 👍

2022-02-15 07:52 UTC, VeeneshJeena commented on src/main/java/io/electrum/vas/model/Transaction.java
> +      }
The idea of setting it to an empty list is simply because we don't want an actual `null` value, and it really isn't intended for clearing the list. 
It's more of a defensive thing on our side, since we're controlling what can and can't be set using the setter method, and in our case for Transaction, we're saying, TransactionLabels can never be null, and in the worst case, it will just be empty, so if you try setting to null, we won't allow it. We're not going to throw an exception, since this isn't really an exceptional case, but we will just clear the list.

I do agree on having a clear contract for purposefully clearing the list. Doing it through the setter is more of a side effect of us guarding ourselves against `null`.

2022-02-15 08:25 UTC, CaseyODonnell92 commented on src/main/java/io/electrum/vas/model/Transaction.java
> +      }
You reckon the `@NotNull` annotation on the parameter isn't sufficient?

2022-02-15 09:07 UTC, mpendulocele-electrum commented on src/main/java/io/electrum/vas/model/TransactionLabel.java
> +   public String getValue() {
What about the length of this value?

2022-02-15 11:12 UTC, CaseyODonnell92 commented on src/main/java/io/electrum/vas/model/TransactionLabel.java
> +   public String getValue() {
I definitely think we should cap it. Let's go with 100 as well?

2022-02-15 11:58 UTC, mpendulocele-electrum commented on src/main/java/io/electrum/vas/model/TransactionLabel.java
> +   public String getValue() {
Done

2022-02-16 07:29 UTC, CaseyODonnell92 requested changes
Realised that we actually have to allow the value to be null, at least for validation. Other than that, I am happy! Let's just check that @VeeneshJeena is too

2022-02-16 07:29 UTC, CaseyODonnell92 commented on src/main/java/io/electrum/vas/model/Transaction.java
> +   @NotNull
I just realised that this breaks backwards compatibility 🤦🏻‍♂️. So I think we can't mandate that this field be non-null.

2022-02-16 07:39 UTC, mpendulocele-electrum commented on src/main/java/io/electrum/vas/model/Transaction.java
> +   @NotNull
I don't think it does, since a default non-null value is set (an empty list).

APIs that do not care about this field can will continue working without any effort added.

2022-02-16 07:52 UTC, CaseyODonnell92 commented on src/main/java/io/electrum/vas/model/Transaction.java
> +   @NotNull
That's true when you construct it within your application. If we introduce this rule (that all transactions must have a non-null list of labels) to existing servers, they will use this new rule to validate requests coming in over the network. Clients that previously sent no/null lists of labels will now be told their requests are invalid.

2022-02-17 15:23 UTC, VeeneshJeena commented on src/docs/devguide/hugo/site/content/release-notes.md
> +Released 16 February 2022
Date reminder

2022-02-17 15:25 UTC, VeeneshJeena approved these changes

2022-02-17 17:13 UTC, merged