Feature add error detail interface
electrumpayments/service-interface-base pull request #73
Opened 2022-03-22 06:36 UTC by hnorrie16

2022-04-06 08:20 UTC, HarryGHeathcock approved these changes
Looks good overall, just a couple of suggestions on comment wording and standard reminders. Shall approve, just implement the suggestions before squashing and merging.

2022-04-11 12:25 UTC, hnorrie16 commented on pom.xml
> +  <version>3.39.0-RC2</version>
Done.

2022-04-11 12:25 UTC, hnorrie16 commented on src/docs/devguide/hugo/site/content/release-notes.md
> +Released 22 March 2022
Done.

2022-04-11 12:25 UTC, hnorrie16 commented on src/main/java/io/electrum/vas/interfaces/IErrorDetail.java
> + */
Done.

2022-04-14 14:21 UTC, sowen123 requested changes
I've made a suggestion on how you can test this. If you change the base ErrorDetail to implement your interface then you can use that to test your interface :) Please can you do that and look at my other comments too

2022-04-14 14:21 UTC, sowen123 commented on src/main/java/io/electrum/vas/interfaces/IErrorDetail.java
>      String getId();
This PR is looking weird on my computer I don't know why I see it is actually in your code

2022-04-14 14:21 UTC, sowen123 commented on src/main/java/io/electrum/vas/interfaces/IErrorDetail.java
>      void setOriginalId(String originalId);
This PR is looking weird on my computer I don't know why I see it is actually in your code

2022-04-14 14:21 UTC, sowen123 commented on src/main/java/io/electrum/vas/interfaces/IErrorDetail.java
so I would suggest you make this interface generic and then use that to return the error type so: `T getErrorType();` and `void setErrorType(T errorType);`

2022-05-09 11:02 UTC, hnorrie16 commented on src/main/java/io/electrum/vas/interfaces/IErrorDetail.java
>      String getId();
Ah okie can confirm it is in my code.

2022-05-09 11:02 UTC, hnorrie16 commented on src/main/java/io/electrum/vas/interfaces/IErrorDetail.java
>      void setOriginalId(String originalId);
Same comment as above.

2022-05-09 11:51 UTC, hnorrie16 commented on src/main/java/io/electrum/vas/model/Transaction.java
> +   protected List<TransactionLabel> transactionLabels = null;
![Screenshot 2022-05-09 at 13 50 34](https://user-images.githubusercontent.com/47846346/167404237-e4bb34ce-20af-4d7b-b997-5092bec14508.png)
wrt. this change, please see the image attacthed.

2022-05-10 07:07 UTC, hnorrie16 commented on src/main/java/io/electrum/vas/interfaces/IErrorDetail.java
>      void setOriginalId(String originalId);
![Screenshot 2022-05-10 at 09 06 49](https://user-images.githubusercontent.com/47846346/167568739-857e33f4-fbdc-4f04-bf26-017136036328.png)

Just incase you can't see it again, this is the look of my interface

2022-05-10 07:08 UTC, hnorrie16 reviewed
Changes made. Enjoy :) 
Please note there are one or two formatting issues I tried to fix. Not sure how to go about this autoformatter.

2022-05-10 07:45 UTC, TimElectrum requested changes

2022-05-10 07:45 UTC, TimElectrum commented on src/docs/devguide/hugo/site/content/release-notes.md
> +* Made `transaction labels` for `Transaction` a null-able field.
`transaction labels` (two words) is not a valid field. Please use the actual field name in the monospaced text

2022-05-10 07:45 UTC, TimElectrum commented on src/docs/devguide/hugo/site/content/release-notes.md
> +*
rogue bullet point

2022-05-10 07:45 UTC, TimElectrum commented on src/docs/devguide/hugo/site/content/release-notes.md
> +    * Changed the format of `toString` output for `AccountPayment` model to match the general format of `toString` for other models.
were these whitespace changes really necessary? Be careful of including a lot of formatting changes in a PR - they make it very noisy and can hide functional changes

2022-05-10 07:45 UTC, TimElectrum commented on src/docs/devguide/hugo/site/content/release-notes.md
> +Version history prior to v3.16.0 can be obtained from the Git commit logs.
what changed on this line?

2022-05-10 07:45 UTC, TimElectrum commented on src/main/java/io/electrum/vas/example/model/ErrorDetail.java
> +public class ErrorDetail implements IErrorDetail {
there's a lot here that's marked as changed in your PR but doesn't appear to have actually changed. Please figure out why and fix it because it's very difficult to see what's an actual change (e.g. specifying `implements IErrorDetail` on line 10) vs non-functional changes (e.g. whatever changed on line 23)

2022-05-10 07:45 UTC, TimElectrum commented on src/main/java/io/electrum/vas/example/model/ErrorDetail.java
> +    private String originalId;
please follow the precedent and init these to `null`

2022-05-10 07:45 UTC, TimElectrum commented on src/main/java/io/electrum/vas/example/model/ErrorDetail.java
> +    }
please add methods of the form below to support method chaining

```
public ErrorDetail property(String propertyValue){
   this.property = propertyValue;
   return this;
}

2022-05-10 07:45 UTC, TimElectrum commented on src/main/java/io/electrum/vas/interfaces/IErrorDetail.java
> +public interface IErrorDetail {
please add the methods to support method chaining

2022-05-10 07:45 UTC, TimElectrum commented on src/main/java/io/electrum/vas/model/Transaction.java
> +   protected List<TransactionLabel> transactionLabels = null;
not sure I agree with this. This is a breaking change in our interface and risks triggering a bunch of NPEs in places where we didn't null-check this field because it was initialised to an empty list by default.

If Capitec have a super-restrictive check on messages and they disallow fields they haven't seen before then we should instead explicitly set those fields to null before sending the message to Capitec. I don't like making a breaking change in our base API just to suit Capitec's own requirements

2022-05-10 09:02 UTC, hnorrie16 commented on src/main/java/io/electrum/vas/example/model/ErrorDetail.java
> +public class ErrorDetail implements IErrorDetail {
Heyo Tim. It's very frustrating my code auto formats as such. I have fixed this small formatting errors.

2022-05-10 09:03 UTC, hnorrie16 commented on src/docs/devguide/hugo/site/content/release-notes.md
> +* Made `transaction labels` for `Transaction` a null-able field.
Done. Though this does conflict with the last point of your review. But that change was made by Natasha and has been pushed to master already. I would suggest chatting to her wrt this change :)

2022-05-10 09:19 UTC, hnorrie16 commented on src/main/java/io/electrum/vas/example/model/ErrorDetail.java
> +    }
Added for all properties. I didn't know this is how it's done. You learn something new everyday :)

2022-05-11 09:16 UTC, hnorrie16 commented on src/main/java/io/electrum/vas/interfaces/IErrorDetail.java
Waiting on you and Harry wrt this

2022-05-13 12:29 UTC, hnorrie16 commented on src/main/java/io/electrum/vas/interfaces/IErrorDetail.java
Thanks for speaking to Casey and Tim. Generics have now been implemented at the class level. Thank you.

2022-05-13 12:35 UTC, hnorrie16 commented on src/main/java/io/electrum/vas/interfaces/IErrorDetail.java
> +public interface IErrorDetail {
Done.

2022-05-13 12:40 UTC, hnorrie16 commented on src/docs/devguide/hugo/site/content/release-notes.md
> +    * Changed the format of `toString` output for `AccountPayment` model to match the general format of `toString` for other models.
Noted.

2022-05-13 12:47 UTC, hnorrie16 commented on src/docs/devguide/hugo/site/content/release-notes.md
> +Released 11 April 2022
Will do upon release :)

2022-05-13 12:47 UTC, hnorrie16 commented on src/docs/devguide/hugo/site/content/release-notes.md
> +
Done - Twas the autoformatter

2022-05-13 12:48 UTC, hnorrie16 commented on src/main/java/io/electrum/vas/example/model/ErrorDetail.java
>  public class ErrorDetail {
Done.

2022-05-13 12:48 UTC, hnorrie16 commented on src/main/java/io/electrum/vas/example/model/ErrorDetail.java
> +    }
Formatter as always... fixed though.

2022-05-16 09:05 UTC, hnorrie16 commented on src/main/java/io/electrum/vas/interfaces/IErrorDetail.java
I.e. Done.

2022-05-16 10:42 UTC, hnorrie16 commented on pom.xml
> +  <version>3.39.0-RC3</version>
Will do upon release :)

2022-05-16 13:16 UTC, sowen123 requested changes

2022-05-16 13:16 UTC, sowen123 commented on src/test/java/io/electrum/vas/model/NewModelTests.java
> +                //@formatter:on
Let's fix your formatting again 😂

2022-05-16 13:16 UTC, sowen123 commented on src/test/java/io/electrum/vas/model/NewModelTests.java
> +                {transactionLabel},
And again

2022-05-16 13:16 UTC, sowen123 commented on src/test/java/io/electrum/vas/model/NewModelTests.java
> +                //@formatter:on
Did you add an error detail in here?

2022-05-16 15:10 UTC, sowen123 approved these changes
LGTM :)

2022-05-16 15:15 UTC, merged