Feature add error detail interface - bug fix in 3.39.1
electrumpayments/service-interface-base pull request #79
Opened 2022-06-03 13:30 UTC by hnorrie16

2022-06-07 11:53 UTC, sowen123 requested changes
Please add tests!

2022-06-07 11:53 UTC, sowen123 commented on pom.xml
> +  <version>3.39.2-RC2</version>
Remember to remove

2022-06-07 11:53 UTC, sowen123 commented on src/docs/devguide/hugo/site/content/release-notes.md
> +Released 01 June 2022
Date reminder

2022-06-07 11:53 UTC, sowen123 commented on src/docs/devguide/hugo/site/content/release-notes.md
> +* Bug fix: The argument type of the `detailMessage()` builder method in the `IErrorDetail` interface was incorrect. It has been changed to type `Object`
```suggestion
* Bug fix: The argument type of the `detailMessage()` builder method in the `IErrorDetail` interface was incorrect. It has been changed to a `Object` from a `String`
```

2022-06-07 11:55 UTC, hnorrie16 commented on src/docs/devguide/hugo/site/content/release-notes.md
> +* Bug fix: The argument type of the `detailMessage()` builder method in the `IErrorDetail` interface was incorrect. It has been changed to type `Object`
Fixed.

2022-06-08 08:57 UTC, hnorrie16 commented on pom.xml
> +  <version>3.39.2-RC2</version>
Removed.

2022-06-08 08:58 UTC, hnorrie16 commented on src/docs/devguide/hugo/site/content/release-notes.md
> +Released 01 June 2022
Updated.

2022-06-29 15:09 UTC, sowen123 commented on src/main/java/io/electrum/vas/example/model/ErrorDetail.java
> +        return sb.toString();
Is your formatter wrong or was this wrong before? The toString has also changed here, why did you change it?

2022-06-30 10:41 UTC, hnorrie16 commented on pom.xml
> +  <version>3.39.2-RC4</version>
Removed.
I am unsure of how to go about this, am I meant to submit with the "RC" and then wait for releasing to remove it, or should I remove the "RC" from the get go?

2022-06-30 10:44 UTC, hnorrie16 commented on src/docs/devguide/hugo/site/content/release-notes.md
> +Released 08 June 2022
Fixed.

2022-06-30 10:44 UTC, hnorrie16 commented on src/docs/devguide/hugo/site/content/release-notes.md
> +* Bug fix: The argument type of the `detailMessage()` builder method in the `IErrorDetail` interface was incorrect. It has been changed to a `Object` from a `String`.
Haha all good!
Fixed.

2022-06-30 10:46 UTC, hnorrie16 commented on src/main/java/io/electrum/vas/example/model/ErrorDetail.java
> +    @ApiModelProperty(value = "")
Fixed.

2022-06-30 11:21 UTC, hnorrie16 reviewed
Review changed implemented.

2022-06-30 14:05 UTC, sowen123 approved these changes
LGTM :)

2022-06-30 14:35 UTC, merged